const B = "";

const SPRITES = [
  { name:"Water",      dot:"#378ADD", cost:100,  ab:"Shield for squadmates in water.",             noV:false, imgs:{b:"Water_Sprite_Fortnite_FNSpots.webp",      go:"Gold_Water_Sprite_FORTNITE_fnspots.webp",      gu:"Gummy_Water_Sprite_FORTNITE_fnspots.webp",      ga:"Galaxy_Water_Sprite_FORTNITE_fnspots.webp",      h:"Holofoil_Water_Sprite_FORTNITE_fnspots.webp",   ge:"Gem_Water_Sprite_FORTNITE_fnspots.webp"      }},
  { name:"Earth",      dot:"#639922", cost:100,  ab:"Higher chance of rare items from chests.",    noV:false, imgs:{b:"Earth_Sprite_FORTNITE_fnspots.webp",       go:"",                                             gu:"Gummy_Earth_Sprite_FORTNITE_fnspots.webp",      ga:"Galaxy_Earth_Sprite_FORTNITE_fnspots.webp",      h:"",                                              ge:"Gem_Earth_Sprite_FORTNITE_fnspots.webp"      }},
  { name:"Fire",       dot:"#D85A30", cost:100,  ab:"Fiery burst after dealing enough damage.",    noV:false, imgs:{b:"Fire_Sprite_Fortnite_FNSpots.webp",        go:"Gold_Fire_Sprite_FORTNITE_fnspots.webp",       gu:"Gummy_Fire_Sprite_FORTNITE_fnspots.webp",       ga:"Galaxy_Fire_Sprite_FORTNITE_fnspots.webp",       h:"Holofoil_Fire_Sprite_FORTNITE_fnspots.webp",    ge:""                                            }},
  { name:"Air",        dot:"#9FE1CB", cost:100,  ab:"Faster sprinting and higher jump height.",    noV:false, imgs:{b:"Air_Sprite_FORTNITE_fnspots.webp",         go:"",                                             gu:"",                                              ga:"",                                               h:"Holofoil_Air_Sprite_FORTNITE_fnspots.webp",     ge:""                                            }},
  { name:"Fishy",      dot:"#1D9E75", cost:100,  ab:"Swim faster, speed boost when damaged.",      noV:false, imgs:{b:"Fishy_Sprite_Fortnite_FNSpots.webp",       go:"",                                             gu:"",                                              ga:"",                                               h:"",                                              ge:""                                            }},
  { name:"Duck",       dot:"#7F77DD", cost:3000, ab:"Emoting or Jamming replenishes shields.",     noV:false, imgs:{b:"Duck_Sprite_Fortnite_FNSpots.webp",        go:"Gold_Duck_Sprite_FORTNITE_fnspots.webp",       gu:"Gummy_Duck_Sprite_FORTNITE_fnspots.webp",       ga:"Galaxy_Duck_Sprite_FORTNITE_fnspots.webp",       h:"Holofoil_Duck_Sprite_FORTNITE_fnspots.webp",    ge:"Gem_Duck_Sprite_FORTNITE_fnspots.webp"       }},
  { name:"Demon",      dot:"#D4537E", cost:3000, ab:"Siphon on eliminating an opponent.",          noV:false, imgs:{b:"Demon_Sprite_FORTNITE_fnspots.webp",       go:"Gold_Demon_Sprite_FORTNITE_fnspots.webp",      gu:"Gummy_Demon_Sprite_FORTNITE_fnspots.webp",      ga:"Galaxy_Demon_Sprite_FORTNITE_fnspots.webp",      h:"",                                              ge:"Gem_Demon_Sprite_FORTNITE_fnspots.webp"      }},
  { name:"Ghost",      dot:"#888780", cost:3000, ab:"Cloak for short duration on reload.",         noV:false, imgs:{b:"Ghost_Sprite_Fortnite_FNSpots.webp",       go:"Gold_Ghost_Sprite_FORTNITE_fnspots.webp",      gu:"Gummy_Ghost_Sprite_FORTNITE_fnspots.webp",      ga:"Galaxy_Ghost_Sprite_FORTNITE_fnspots.webp",      h:"Holofoil_Ghost_Sprite_FORTNITE_fnspots.webp",   ge:"Gem_Ghost_Sprite_FORTNITE_fnspots.webp"      }},
  { name:"King",       dot:"#EF9F27", cost:3000, ab:"Increased Pickaxe damage.",                   noV:false, imgs:{b:"King_Sprite_FORTNITE_fnspots.webp",        go:"Gold_King_Sprite_FORTNITE_fnspots.webp",       gu:"Gummy_King_Sprite_FORTNITE_fnspots.webp",       ga:"Galaxy_King_Sprite_FORTNITE_fnspots.webp",       h:"Holofoil_King_Sprite_FORTNITE_fnspots.webp",    ge:""                                            }},
  { name:"Striker",    dot:"#D85A30", cost:3000, ab:"Overdrive on mantle, hurdle, wall scramble.", noV:false, imgs:{b:"Striker_Sprite_FORTNITE_fnspots.webp",     go:"",                                             gu:"",                                              ga:"",                                               h:"Holofoil_Striker_Sprite_FORTNITE_fnspots.webp", ge:""                                            }},
  { name:"Aura",       dot:"#B5D4F4", cost:3000, ab:"Shock Rock charge on enough damage dealt.",   noV:false, imgs:{b:"Aura_Sprite_FORTNITE_fnspots.webp",        go:"",                                             gu:"",                                              ga:"",                                               h:"",                                              ge:"Gem_Aura_Sprite_FORTNITE_fnspots.webp"       }},
  { name:"Punk",       dot:"#F4C0D1", cost:5000, ab:"Nothing until Lv5 — then unlimited ammo.",    noV:false, imgs:{b:"Punk_Sprite_FORTNITE_fnspots.webp",        go:"Gold_Punk_Sprite_FORTNITE_fnspots.webp",       gu:"Gummy_Punk_Sprite_FORTNITE_fnspots.webp",       ga:"Galaxy_Punk_Sprite_FORTNITE_fnspots.webp",       h:"",                                              ge:"Gem_Punk_Sprite_FORTNITE_fnspots.webp"       }},
  { name:"Dream",      dot:"#CECBF6", cost:5000, ab:"Random item each level. Lv5 = auto-extract.", noV:false, imgs:{b:"Dream_Sprite_FORTNITE_fnspots.webp",       go:"Gold_Dream_Sprite_FORTNITE_fnspots.webp",      gu:"Gummy_Dream_Sprite_FORTNITE_fnspots.webp",      ga:"Galaxy_Dream_Sprite_FORTNITE_fnspots.webp",      h:"",                                              ge:""                                            }},
  { name:"Boss",       dot:"#A32D2D", cost:5000, ab:"Boosts max Health and Shield.",               noV:false, imgs:{b:"Boss_Sprite_FORTNITE_fnspots.webp",        go:"",                                             gu:"",                                              ga:"",                                               h:"",                                              ge:""                                            }},
  { name:"Seven",      dot:"#534AB7", cost:5000, ab:"Enemy foot trails visible for your squad.",   noV:false, imgs:{b:"Seven_Sprite_FORTNITE_fnspots.webp",       go:"",                                             gu:"",                                              ga:"",                                               h:"Holofoil_Seven_Sprite_FORTNITE_fnspots.webp",   ge:""                                            }},
  { name:"Zero Point", dot:"#85B7EB", cost:7500, ab:"Shield Bubble Jr. on healing item use.",      noV:false, imgs:{b:"Zero_Point_Sprite_FORTNITE_fnspots.webp",  go:"Gold_Zero_Point_Sprite_FORTNITE_fnspots.webp", gu:"Gummy_Zero_Point_Sprite_FORTNITE_fnspots.webp", ga:"Galaxy_Zero_Point_Sprite_FORTNITE_fnspots.webp", h:"",                                              ge:"Gem_Zero_Point_Sprite_FORTNITE_fnspots.webp" }},
  { name:"Grim",       dot:"#3B6D11", cost:7500, ab:"Attackers get marked for a duration.",        noV:false, imgs:{b:"Grim_Sprite_FORTNITE_fnspots.webp",        go:"",                                             gu:"",                                              ga:"",                                               h:"",                                              ge:""                                            }},
  { name:"Burnt Peanut",dot:"#BA7517",cost:7500, ab:"Bonus loot (incl. Mythic) from elims. No variants.", noV:true, imgs:{b:"Burnt_Peanut_FORTNITE_fnspots.webp", go:"",                                             gu:"",                                              ga:"",                                               h:"",                                              ge:""                                            }},
];
